spring.application.name=Lab9
spring.datasource.url=jdbc:postgresql://localhost:15432/Tickets
spring.datasource.username=selfcore
spring.datasource.password=secretpassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security=trace

jwt.secret = hJRFCYO6A7N3gY5wL1xNHcJIB9IN/3a+VSjgD0DWUQ4=
jwt.expiration = 3600000